# Change these first
owner: serversshne # Your GitHub organization or username, where this repository lives
repo: status-mainssh.com # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: dedns.mainssh.xyz
    check: "tcp  -ping"
    urlk: dedns.mainssh.xyz
  - name: usdns.mainssh.xyz
    check: "tcp  -ping"
    urlk: usdns.mainssh.xyz
  - name: frdns.mainssh.xyz
    check: "tcp  -ping"
    urlk: frdns.mainssh.xyz
  - name: cadns.mainssh.xyz
    check: "tcp  -ping"
    urlk: cadns.mainssh.xyz
  - name: sg2dns.mainssh.xyz
    check: "tcp  -ping"
    urlk: sg2dns.mainssh.xyz
  - name: sg1dns.mainssh.xyz
    check: "tcp  -ping"
    urlk: sg1dns.mainssh.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor server status for services on jagoanssh"
  introMessage: This is a server status page that uses real-time data  
  navbar:
    - title: Uptime
      href: /
    - title: Home
      href: https://status.mainssh.com
  theme: light
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
